const NOISE_WORDS = new Set([
  "about",
  "advertisement",
  "advertising",
  "afp",
  "agency",
  "agencies",
  "analysis",
  "analyses",
  "ap",
  "article",
  "articles",
  "associated",
  "author",
  "authors",
  "bbc",
  "bloomberg",
  "breaking",
  "caption",
  "cbs",
  "cnn",
  "commentary",
  "copyright",
  "copy",
  "coverage",
  "credit",
  "credits",
  "editor",
  "editors",
  "exclusive",
  "explained",
  "explainer",
  "file",
  "files",
  "forbes",
  "fox",
  "getty",
  "google",
  "guardian",
  "image",
  "images",
  "investigate",
  "investigates",
  "iraq",
  "iraqi",
  "journalist",
  "journalists",
  "latest",
  "listen",
  "live",
  "login",
  "media",
  "msn",
  "nbc",
  "news",
  "newsletter",
  "nytimes",
  "opinion",
  "photo",
  "photos",
  "picture",
  "pictures",
  "podcast",
  "politico",
  "press",
  "promo",
  "publisher",
  "publishers",
  "read",
  "reads",
  "reading",
  "report",
  "reports",
  "reserved",
  "reuters",
  "rights",
  "said",
  "says",
  "sign",
  "source",
  "sources",
  "sponsored",
  "staff",
  "stories",
  "story",
  "stream",
  "subscribe",
  "subscriber",
  "subscribers",
  "subscription",
  "underscored",
  "update",
  "updates",
  "video",
  "videos",
  "watch",
  "website",
  "wire",
  "wires",
  "writer",
  "writers",
  "wsj",
  "yahoo",
]);

const URL_NOISE_WORDS = new Set([
  "amp",
  "ar",
  "aspx",
  "com",
  "details",
  "feed",
  "feeds",
  "html",
  "http",
  "https",
  "iq",
  "key",
  "net",
  "org",
  "rss",
  "url",
  "www",
]);

const SOURCE_NOISE_WORDS = new Set([
  "alhurra",
  "alforatnews",
  "alhadath",
  "aljazeera",
  "alarabiya",
  "alsharqiya",
  "alsumaria",
  "kurdistan24",
  "nina",
  "ninanews",
  "rudaw",
  "shafaq",
  "utv",
  "الاخبار",
  "الاعلام",
  "الاتجاه",
  "الجزيره",
  "الحدث",
  "الحرة",
  "الحره",
  "السومريه",
  "الشرقيه",
  "الفرات",
  "العربيه",
  "المدى",
  "المدي",
  "نينا",
  "نيوز",
  "وكاله",
]);

const ARABIC_STOP_WORDS = new Set([
  "اثر",
  "اذا",
  "اذ",
  "الا",
  "التي",
  "الذي",
  "الذين",
  "اللا",
  "اللتان",
  "اللذان",
  "اللذين",
  "الى",
  "اما",
  "امام",
  "ان",
  "انه",
  "او",
  "اول",
  "اي",
  "ايضا",
  "اين",
  "بعد",
  "بعض",
  "بين",
  "تلك",
  "تم",
  "ثم",
  "حتى",
  "حول",
  "حيث",
  "حين",
  "خلال",
  "دون",
  "ذلك",
  "هذه",
  "هذا",
  "لكن",
  "لدى",
  "لم",
  "لن",
  "له",
  "لها",
  "ما",
  "مع",
  "من",
  "منذ",
  "نحو",
  "هل",
  "هو",
  "هي",
  "وفي",
  "ولا",
  "وقد",
  "وهو",
  "وهي",
  "يكون",
]);

const ARABIC_NEWS_NOISE_WORDS = new Set([
  "ابرز",
  "اخر",
  "اكثر",
  "اعلان",
  "الان",
  "العاجله",
  "العراق",
  "العراقي",
  "العراقيه",
  "الخبر",
  "الخبرتابعونا",
  "العمل",
  "الاولي",
  "الثانيه",
  "الحكومه",
  "الخاصه",
  "اليوم",
  "الرسميه",
  "امس",
  "تحديث",
  "تفاصيل",
  "جديد",
  "جديدة",
  "جديده",
  "خبر",
  "اخبار",
  "اشترك",
  "بالتعاون",
  "رئيس",
  "رييس",
  "سياسه",
  "عاجل",
  "عام",
  "عربي",
  "عربيه",
  "عالمي",
  "عبر",
  "عراق",
  "بغداد",
  "دايره",
  "تطلق",
  "فيديو",
  "قبل",
  "كامل",
  "مصدر",
  "مصادر",
  "نشرة",
  "نشره",
  "مجلس",
  "منصه",
  "قناتنا",
  "وزاره",
  "وزارة",
  "هييه",
]);

const DATE_WORDS = new Set([
  "monday",
  "tuesday",
  "wednesday",
  "thursday",
  "friday",
  "saturday",
  "sunday",
  "january",
  "february",
  "march",
  "april",
  "june",
  "july",
  "august",
  "september",
  "october",
  "november",
  "december",
  "today",
  "yesterday",
  "tomorrow",
  "ago",
  "hour",
  "hours",
  "minute",
  "minutes",
  "day",
  "days",
  "week",
  "weeks",
  "month",
  "months",
  "year",
  "years",
  "الاحد",
  "الاثنين",
  "الثلاثاء",
  "الاربعاء",
  "الخميس",
  "الجمعة",
  "الجمعه",
  "السبت",
  "دقيقه",
  "دقائق",
  "ساعه",
  "ساعات",
  "شهر",
  "عام",
  "اليوم",
  "غدا",
  "غداً",
  "امس",
]);

const NOISE_PHRASES = new Set([
  "associated press",
  "file photo",
  "file photos",
  "getty image",
  "getty images",
  "live updates",
  "news analysis",
  "photo illustration",
  "subscribe newsletter",
  "cnn underscored",
]);

const ALLOWED_SHORT_TERMS = new Set(["ai"]);

function normalizeAnalyticsValue(value: string): string {
  return value
    .normalize("NFKC")
    .toLowerCase()
    .replace(/[إأآٱ]/g, "ا")
    .replace(/ؤ/g, "و")
    .replace(/ئ/g, "ي")
    .replace(/ى/g, "ي")
    .replace(/ة/g, "ه")
    .replace(/[\u064B-\u065F\u0670]/g, "")
    .replace(/\u0640/g, "")
    .replace(/[^a-z0-9\u0600-\u06FF]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function analyticsTokens(value: string): string[] {
  return normalizeAnalyticsValue(value).match(/[a-z0-9\u0600-\u06FF]{2,}/g) || [];
}

function isNoiseToken(token: string): boolean {
  if (!ALLOWED_SHORT_TERMS.has(token) && token.length < 3) return true;
  if (/^\d+$/.test(token)) return true;
  if (/^\d+(?:st|nd|rd|th)$/.test(token)) return true;
  return (
    NOISE_WORDS.has(token) ||
    URL_NOISE_WORDS.has(token) ||
    SOURCE_NOISE_WORDS.has(token) ||
    ARABIC_STOP_WORDS.has(token) ||
    ARABIC_NEWS_NOISE_WORDS.has(token) ||
    DATE_WORDS.has(token)
  );
}

export function isGenericAnalyticsTerm(value: string | null | undefined): boolean {
  if (!value) return true;
  const normalized = normalizeAnalyticsValue(value);
  if (!normalized) return true;
  if (NOISE_PHRASES.has(normalized)) return true;

  const tokens = analyticsTokens(normalized);
  if (tokens.length === 0) return true;
  if (tokens.length === 1) return isNoiseToken(tokens[0]);
  return tokens.every(isNoiseToken);
}
